### ISSUE TITLE
Add Alliance Credits field to Template:AllianceResources

### ISSUE THREAD

**Issue by seasoprano** [Nkmol/RoC-Wiki#19]
There are alliance tech researches that require alliance credits

**Comment by thadius856** [comment]
We must have been on the same brain wave. [I added](https://riseofcivilizations.wikia.com/index.php?title=Template%3AAllianceResources&diff=4300&oldid=3026) Alliance Credits and Individual Credits to Template:AllianceResources about 9 hrs ago, before seeing this. Current params are:

{{AllianceResources|Tech Pts|A.Food|A.Wood|A.Stone|A.Gold|A.Credits|I.Credits}}

It's not pre-filled on any of the alliance tech pages, but you can just throw another pipe (`|`) at the end to use it.

Recommend closure as resolved.
